version: "3"
services:
  nginx:
      image: nginx:1.23.0
      restart: always
      volumes:
          - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
          - /srv/docker/ner/logs:/var/log/nginx/
      ports:
          - 10130:80
      depends_on:
          - frontend
          - backend

  backend:
    image: ner/backend:devel
    restart: always
    build: 
      context: backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      API_VERSION: 1.0.0
      API_ENV: "DEV" # or PROD
      PYTHONPATH: .
    volumes:
      - ./backend/app:/app

  frontend:
    restart: on-failure
    image: ner/frontend:devel
    command: bash -c "npm run build && serve -s build -l tcp://0.0.0.0:3000"
    build:
      context: frontend
      dockerfile: prod.Dockerfile
    container_name: frontend
    environment:
      NODE_ENV: production
      CHOKIDAR_USEPOLLING: "true"